
# SEO settings
title: "Think"
title2: "space"
description: ""
keywords: "jeonsungyun, android, react-native, python"
url: http://jeonsungyun.github.io
baseurl: null # apply null if repo name is something like username.github.io

# google_analytics: UA-XXXXX-XX
repo: https://github.com/JeonSungYun/jeonsungyun.github.io
disqus_shortname: "jeonsungyun"
# twitter_username: "HeiswayiNrird"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Sungyun Jeon"
  job      : "Software Engineer"
  bio      : "Here is many gemstones for us ;)"
  thumb    : /images/author.jpg
  email    : roland.korea@gmail.com
  url      : http://jeonsungyun.github.io
  github   : https://github.com/JeonSungYun
  facebook : https://www.facebook.com/jeonsungyun
  linkedin : https://www.linkedin.com/in/jeonsungyun

# social settings
# og_locale: "en_US"
# twitter_card: "summary_large_image"
# twitter_site: "@HeiswayiNrird"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
